Changes to User Sponsoring Flow - Shifting from Spend to Sponsor
BrightID/BrightID pull request #1197
Opened 2024-01-08 18:27 UTC by sentax

This pull request introduces changes to the user sponsoring flow. The changes aim to change spend sponsorships flow into single step operation

2024-01-09 05:57 UTC, abramsymons commented on BrightID/locales/en/translation.json
> +      "sponsorOpFailed": "sponsor operation failed",
It would be better to use capitalized letters for the messages.

2024-03-18 11:04 UTC, TripleSpeeder reviewed
This looks good to me. I'm running end-2-end tests again, if no problems come this should be fine to be merged.

2024-03-22 08:27 UTC, TripleSpeeder requested changes

2024-03-22 08:27 UTC, TripleSpeeder commented on BrightID/src/components/Apps/appThunks.ts
>      dispatch(
Looks like we don't need the state SPONSOR_PRECHECK_APP anymore, as the operation `api.sponsor` is now submitted without checking if it was submitted already before. 
If my understanding is correct we can delete the state SPONSOR_PRECHECK_APP from the app_linking_steps enum. Transition can go directly from `PRELINK_CHECK_PASSED` to `SPONSOR_WAITING_OP`.

2024-03-29 12:52 UTC, merged